### ISSUE TITLE
template folder missing when installing with yeoman

### ISSUE THREAD

**Issue by eusorov** [ommsolutions/generator-next#4]
npm install -g generator-next

then 
yo next myproj

?Enter your name  abc
? Enter your E-Mail abc@test.com
? Enter the port on which the server should run. 1337

Configuring ...
Writing files ...
events.js:183
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Users\eusorov\AppData\Roaming\npm\node_modules\generator-next\generators\app\templates\package.json
    at EditionInterface.exports.copy (C:\Users\eusorov\AppData\Roaming\npm\node_modules\generator-next\node_modules\mem-fs-editor\lib\actions\copy.js:47:3)
    at EditionInterface.module.exports [as copyTpl] (C:\Users\eusorov\AppData\Roaming\npm\node_modules\generator-next\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:10:8)
    at NExTGenerator.writing (C:\Users\eusorov\AppData\Roaming\npm\node_modules\generator-next\generators\app\index.js:61:17)
    at Object.<anonymous> (C:\Users\eusorov\AppData\Roaming\npm\node_modules\generator-next\node_modules\yeoman-generator\lib\index.js:399:25)
    at C:\Users\eusorov\AppData\Roaming\npm\node_modules\generator-next\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\eusorov\AppData\Roaming\npm\node_modules\generator-next\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\eusorov\AppData\Roaming\npm\node_modules\generator-next\node_modules\yeoman-generator\lib\index.js:400:11)

After manually adding the template Folder to the generator directory everythings worked.

**Comment by enenkel** [comment]
@eusorov Thanks for spotting that! 
The current version (0.3.3) contains the template files again.
